### PR TITLE
Various Fixes and Changes

### PR DESCRIPTION
**Pull request by Rockdtben**
* Allow for door codes to be set via config file `config/door_codes.json`
* Allows for admins to be set via config file `config/admins.json`
* Allows for MOTD text to be displayed on Login() via `config/motd.txt`
* Labs load at world start.
* Labs save every 5 minutes.
* Labs save when admin presses :Reboot
* Fixes a bug in hubs/routers #10 
* Adds the missing tutorial.txt #9 

`door_codes.json` can be used to set door_codes.
`admins.json` can be used to set admins.

**How to use door codes**
While mapping if you set the `doorcode_ref` which acts as a KEY in the `door_codes.json` KEY:VALUE pair list.

### CODE REVIEW

**Comment by Rockdtben** [comment]
Fixes #10 
Fixes #9

**Comment by Nadrew** [comment]
The saves/ directory should be ignored, so I moved the book content (tutorial.txt) into books/ you can do that too. You should also be setting the admins list to list() or checking if it's null in the places where 'in' gets used on it, otherwise an empty JSON config for it (or bad config) is gonna cause runtimes in other places.

**Comment by Nadrew** [comment]
Oh, and it's the old ugly default tutorial.txt that I pushed, so you can definitely put your nicer one up too :P

**Comment by Rockdtben** [comment]
https://github.com/Nadrew/console/pull/8/commits/03b152807b823b77f75aa91546b29d6f9aba2329

**Comment by Rockdtben** [comment]
I'll be splitting these up into their on self contained PRs.

**Comment by Rockdtben** [comment]
Tutorial.txt #11

**Pull request merged**
